kind: Secret
apiVersion: v1
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:Uc1dHHOcmNCh3E4dJ7Q0KmH4jPAhAPZsaMpGV91IdSoi5NDyJor+XJo+JjT0D9/r9mOP6g==,iv:fW1X4N10ws0gnKN6XFaiz4qLGS48xK6hXt7a9wDfCFU=,tag:1Ysels1YVihvagDzyvnXrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-24T02:31:30Z"
    mac: ENC[AES256_GCM,data:LIxxU52PmjoKB31TdXWDuCbNYs22Sujny8J5FyhP2Ok6RneQ7PoBsqe7OGyymGIN7gCZRBKbxMatFJODQDtQWAA18jMZc3jisWmbhIu7ZLVn8eM81DFT2V9gJXJQfvhjfrqBHV575B5zEsR9yYbcm/xYYRUYOwsmx9i+/SYQiy8=,iv:SDSBxnwLmrI7NPuZIlmOMj82OBfVhAoqiDBUoCY+TrA=,tag:6V+qbWiW/XhBwLbtIH/OFw==,type:str]
    pgp:
        - created_at: "2022-05-24T02:31:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0n6xN/iRWUrARAAghpYoXfjnswqWJKIzIIpEjJ1ipslCd2g8Rx8bSjCxrUz
            eBGBQrqzDeR7ehHDfh4e3HLznJYcUEDwd4DBoIXsp/tPO3pSk9mThQiLe0UPmqCp
            afXWyLkg3NSn3tNAYRYlD0ZH5HY9q74Jv6KPlrIkaqsCY/h7MxJjZH6XgM/GJmul
            xrYUzFYXtVWpKDYCvkjQkGH7N9DMEZxnD++wrA2hhx6Xrz5UZatJByErSmrUeHv6
            qJPemb2v3k26oqiVWYXFH5Rces50NinxSKr13TsoVYYRusDIl7g/UB2VqZVw00+X
            X1JsSri+zcO8f4paVXwLc5SNc+uaBETtXYZH4atphnQ5bWbNzizahOOQIV3w4LzQ
            jVJiPTIrqIeat6y19BeNDe1ir2k2qmtycqMivmDrPbG7G8q1Y1wFOYiQqA8Cx2K5
            RwZGrK/EBN1XasMmbzv/sPsQDKyzHgnTXSrhKjk89BRUM40S6yq85+3g4bZcHV0b
            y4UPxoBdIKdI03gjz7yIk8ZsYbmiztPDfoxxhp49bum8Wx6pYYZ08AkeGC6SFFPc
            J70NtucZUDQuyxjmaj7jpcjvLsxzwJR2I9Kpu+Rf5tn+6m1qhcWkiXnkp/aG1482
            9eJeqUsS5kED4AAVWeI4OcZn0wJ4KyudxfSs1Z+I2sf35PMq3ldSQSXMLcS0PlvS
            XgEq+mHZxccp66qHD7bBFIw3me/a+gp0+gLT9IXYAY6FZzvLe/yLNUgNTgYsQKpU
            M3V4ecZ2+iRH+lyN0oQy/E+PTGh9Dn7B9PCKnupwaAjGYrzbEterdpIW1vpiP6o=
            =0rFw
            -----END PGP MESSAGE-----
          fp: F77F35FF1FB27EC0C3ED42C8487CC4DD380B8B28
    encrypted_regex: ^(stringData|data)$
    version: 3.7.3
